version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - node_express

  node_express:
    image: node:6.9-alpine
    container_name: node_express
    hostname: node_express
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm start]
    ports:
      - "3000:3000"
    links:
      - mysql

  # mysql:
  #   image: mysql:5.6
  #   container_name: mysql56
  #   hostname: mysql
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=root"
  #     - "MYSQL_DATABASE=sample"