version: '3'
services:
  app:
    build: .
    image: panda-book                  # イメージ名
    container_name: panda-book         # コンテナ名
    ports:                          # ポート接続
      - 3000:3000
    volumes:                        # mount workdir
      - ./:/src
    command: [sh, -c, npm install && npm start:node]
    